### ISSUE TITLE
bug 请求帮助

### ISSUE THREAD

**Issue by hdtechfinance5510** [yy1300326388/flutter_drink_login_app#1]
您好，我是新手，发现你的登陆页面非常漂亮，iphone12 真机测试后报bottom overflowed by 303pixels，登陆页面输入用户名报错误，在Scaffold中增加resizeToAvoidBottomInset: false, 不报错了。但是输入键盘总是遮挡住密码框，网上找了很多方法都没有解决。请问你能解决吗？

**Comment by BytesZero** [comment]
@hdtechfinance5510 
你好，首先未你的学习和提问点赞，这里问题我再掘金文章中回复过了，可以看看update 分支的改动，你这里提到键盘适配的问题，这个是一个较大的话题，不同情况和需求都不一样，所以可以先继续学习看看，实际项目遇到再进一步学习即可

<img width="781" alt="image" src="https://user-images.githubusercontent.com/8764899/194691983-e54c68c4-d460-4102-9aaa-c06cf80324b6.png">
